// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHd3jhTVZzp5Y2y9BHcdVBg8h-GOpzdYM',
    appId: '1:558124551253:web:152dff18a1655e980058dc',
    messagingSenderId: '558124551253',
    projectId: 'lumanime-app',
    authDomain: 'lumanime-app.firebaseapp.com',
    storageBucket: 'lumanime-app.firebasestorage.app',
    measurementId: 'G-GNXPK4QQ82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvy8Wt8LHhYJOhXXuG-xzPtOvk5Sp3wYM',
    appId: '1:558124551253:android:0a73fd6c52274e920058dc',
    messagingSenderId: '558124551253',
    projectId: 'lumanime-app',
    storageBucket: 'lumanime-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8WgsF9F3jN7oidecPQQkqAuFIHobW2sY',
    appId: '1:558124551253:ios:41f584f773e279760058dc',
    messagingSenderId: '558124551253',
    projectId: 'lumanime-app',
    storageBucket: 'lumanime-app.firebasestorage.app',
    iosBundleId: 'com.example.lumaNomeApp',
  );
}
